<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <ApplicationInsightsResourceId>/subscriptions/c1e427eb-9653-40f1-b269-7623cab18fb1/resourceGroups/Money2Word/providers/microsoft.insights/components/Money2Word</ApplicationInsightsResourceId>
    <UserSecretsId>c781ab72-9cf1-40f9-98da-391b2c5e0ebb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>
