trigger:
- '*'
pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildJob
    displayName: 'Build & Publish Artifact'
    steps:
    - checkout: self
      displayName: 'Checkout repository'
    - template: build-template.yml
      parameters:
        dotnetSdkVersion: '9.0.x'          # change if needed
        projects: '**/*.csproj'            
        configuration: 'Release'
        testProjects: '**/*Tests/*.csproj' # set to '' to skip tests
        publishFolder: '$(Build.ArtifactStagingDirectory)/publish'
        artifactName: 'drop'
        zipName: 'Money2Word.zip'
