trigger:
  branches:
    include:
      - develop
pr:
  branches:
    include:
      - develop

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    displayName: Build & Publish
    steps:
    - template: build-template.yml
      parameters:
        solution: '**/*.sln'
        configuration: 'Release'
