trigger: none 

pool:
  vmImage: windows-latest

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    displayName: Build & Publish
    steps:
    - template: templates/build-steps.yml
      parameters:
        solution: '**/*.sln'
        configuration: 'Release'

- stage: Deploy
  displayName: Deploy To Azure
  dependsOn:
  - Build
  jobs:
  - deployment: DeployToAppService
    environment:
      name: Prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: drop
              path: $(Pipeline.Workspace)

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: AzureRM
              azureSubscription: Money2Word Subscription (bc4f6c10-16bf-4bd6-abf7-7a02968bcd39)
              appType: webApp
              WebAppName: Money2Word
              package: $(Pipeline.Workspace)/drop/Money2Word.zip
