trigger:
  branches:
    include:
    - develop
pool:
  vmImage: 'windows-latest'
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: Money2WordCore.sln
    - task: VSBuild@1
      inputs:
        solution: Money2WordCore.sln
        msbuildArgs: >
          /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"
        platform: Any CPU
        configuration: Release
        clean: true
    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\*test*.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        platform: Any CPU
        configuration: Release
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Deploy
  dependsOn:
  - Build
  jobs:
  - deployment: DeployToAppService
    environment:
      name: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Money2Word Subscription (bc4f6c10-16bf-4bd6-abf7-7a02968bcd39)'
              appType: 'webApp'
              WebAppName: 'Money2Word'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


