trigger:
- '*'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'CI Build'
  jobs:
  - job: BuildJob
    steps:
    - template: .azure-pipelines/build-template.yml
      parameters:
        solution: '$(Build.SourcesDirectory)/money2word.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'